### ISSUE TITLE
Use existing environment variables when interpolating

### ISSUE THREAD

**Issue by Tantalon** [cardinalby/export-env-action#1]
It would be great if we could use existing environment variables when interpolating variables.

This would allow us to use the GitHub environment variables to do things like:
`STACK_PREFIX=demo-$GITHUB_RUN_ATTEMPT`

I had a look into how to implement this, and based on these:
1. dotenv-expand normally uses process.env when interpolating, but not if `ignoreProcessEnv: true` is set
2. removing `ignoreProcessEnv: true` means all outputs will also be written to process.env
3. GitHub only persists environment variables written using the API, any environment variables directly set are ignored

I believe removing `ignoreProcessEnv: true` should be safe to do and all that's needed to achieve this.

**Comment by cardinalby** [comment]
Hi! Thanks for the idea. In order to not break the compatibility I suggest introducing the new "considerStepEnv" (or smth like this) input with default value = 'false'. 

If I have time I will implement it soon. Help me please with the proper name for the input :)

**Comment by Tantalon** [comment]
Thanks @cardinalby! How about "inheritEnvironment" or "useJobEnv"?

**Comment by cardinalby** [comment]
Using of the new input makes sense only if it is used together with `expand: true` so I suggest naming it `expandWithJobEnv`

**Comment by cardinalby** [comment]
@Tantalon Please check out the new version

**Comment by Tantalon** [comment]
Tested and it works great, thanks @cardinalby!
