### ISSUE TITLE
Add option to mask as secret all environment values exported

### ISSUE THREAD

**Issue by hohoaisan** [cardinalby/export-env-action#5]
As in the title, the env was loaded should have an option to mask it as secret to avoid Github Action list them in the logs. For most env I can do workaround by bash script, but multiline env is quite challenging.

**Comment by hohoaisan** [comment]
Document about masking values as secret https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-log

**Comment by cardinalby** [comment]
Hi! I have added this option, use `mask: true` input to mask all values as secrets.

I don't know your case, but keep in mind that it is a bad idea to store secrets in `.env` file in the repo, use [GitHub secrets](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-encrypted-secrets-for-your-repository-and-organization-for-github-codespaces) for that purpose.

**Comment by hohoaisan** [comment]
Thanks!
